esphome:
  name: standing-desk
  platform: ESP8266
  board: d1_mini

logger:
  level: DEBUG

packages:
  standing_desk: github://tjhorner/esphome-standing-desk/configs/template.yaml
  desk_config: github://tjhorner/esphome-standing-desk/configs/desks/DESK_BRAND.yaml

wifi:
  ap:
    ssid: "Standing Desk Controller"
    password: "hunter2hunter2"

captive_portal:

improv_serial:

api:
  password: ""
  reboot_timeout: 0s

web_server:
  port: 80

ota:
  password: ""
